#!/usr/bin/env bash
# Website Assistant installer: the only terminal step.
#   ./install.sh
# Optional overrides: APP_PORT=8000 ADMIN_PORT=8001 ./install.sh
set -euo pipefail
cd "$(dirname "$0")"

info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# Use sudo for privileged commands when not running as root.
SUDO=""
if [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1; then SUDO="sudo"; fi

# --- 1. Docker ---------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
    if [ "$(uname -s)" = "Linux" ]; then
        read -r -p "Docker is not installed. Install it now with Docker's official script? [y/N] " answer
        case "$answer" in
            y|Y|yes|YES)
                command -v curl >/dev/null 2>&1 || die "curl is required to install Docker"
                curl -fsSL https://get.docker.com | $SUDO sh
                $SUDO systemctl enable --now docker 2>/dev/null || true
                ;;
            *) die "Docker is required. See https://docs.docker.com/engine/install/" ;;
        esac
    else
        die "Docker is required. Install Docker Desktop: https://docs.docker.com/get-docker/"
    fi
fi

docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required (the 'docker compose' plugin)."

DOCKER="docker"
if ! docker info >/dev/null 2>&1; then
    if [ -n "$SUDO" ] && $SUDO docker info >/dev/null 2>&1; then
        DOCKER="$SUDO docker"
        warn "Using sudo for Docker. Add your user to the 'docker' group to avoid this."
    else
        die "Docker is installed but not running (start Docker / Docker Desktop and retry)."
    fi
fi

# --- 2. .env ------------------------------------------------------------------
rand_hex() {
    # $1 = number of random bytes
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$1"
    else
        head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
}

if [ -f .env ]; then
    # Never regenerate: a new SECRET_KEY would make stored API keys unreadable,
    # and a new DB password would no longer match the existing database.
    info "Keeping existing .env"
else
    info "Creating .env with random secrets"
    db_password="$(rand_hex 24)"
    umask 077
    cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). See .env.example for all options.
POSTGRES_USER=chatbot
POSTGRES_DB=chatbot
POSTGRES_PASSWORD=${db_password}
DATABASE_URL=postgresql+psycopg://chatbot:${db_password}@db:5432/chatbot
SECRET_KEY=$(rand_hex 32)
APP_PORT=${APP_PORT:-8000}
ADMIN_PORT=${ADMIN_PORT:-8001}
EOF
    umask 022
fi

# Load ports from .env (it may pre-date this run).
set -a
# shellcheck disable=SC1091
. ./.env
set +a
APP_PORT="${APP_PORT:-8000}"
ADMIN_PORT="${ADMIN_PORT:-8001}"

mkdir -p "${WATCHED_HOST_DIR:-./watched}"

# --- 3. Start -------------------------------------------------------------------
info "Building and starting containers (the first run can take several minutes)"
$DOCKER compose up -d --build

# --- 4. Wait for health -------------------------------------------------------------
info "Waiting for the application to become healthy"
healthy=0
for _ in $(seq 1 60); do
    if $DOCKER compose exec -T app python -m app.healthcheck >/dev/null 2>&1; then
        healthy=1
        break
    fi
    sleep 3
done
[ "$healthy" -eq 1 ] || die "The app did not become healthy. Check: $DOCKER compose logs app"

# --- 5. Done --------------------------------------------------------------------------
server="$( (hostname -I 2>/dev/null || true) | awk '{print $1}')"  # -I is Linux-only
server="${server:-localhost}"
echo
info "Website Assistant is running."
echo "    Open http://${server}:${ADMIN_PORT}/setup to finish setup"
echo "    Public chat API / widget: http://${server}:${APP_PORT}"
